services:

  postgres:
    image: postgres:16
    container_name: ctc_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
  backend:
    build: ./backend
    container_name: ctc_backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
volumes:
  postgres_data: