from app.models.user import User
from app.models.role import Role
from app.models.student import Student
from app.models.diploma import Diploma
from app.models.schedule import Schedule
from app.models.enrollment import Enrollment
from app.models.payment import Payment
from app.models.cash_register import CashRegister
from app.models.institution_config import InstitutionConfig