"""recreate students table

Revision ID: 2f726266858e
Revises: 5c5f06665f0f
Create Date: 2026-07-28 02:16:20.987664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f726266858e'
down_revision: Union[str, Sequence[str], None] = '5c5f06665f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=False),
    sa.Column('dui', sa.String(length=10), nullable=True),
    sa.Column('guardian_name', sa.String(length=150), nullable=False),
    sa.Column('guardian_dui', sa.String(length=10), nullable=False),
    sa.Column('guardian_relationship', sa.String(length=50), nullable=False),
    sa.Column('guardian_email', sa.String(length=120), nullable=True),
    sa.Column('guardian_whatsapp', sa.String(length=15), nullable=True),
    sa.Column('observations', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dui'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
