"""add dates to enrollment

Revision ID: fb4964b14f84
Revises: ace1c3c056f9
Create Date: 2026-07-28 15:08:22.080809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4964b14f84'
down_revision: Union[str, Sequence[str], None] = '94da45e90646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('enrollments', sa.Column('end_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'end_date')
    op.drop_column('enrollments', 'start_date')
    # ### end Alembic commands ###
